version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 846634201516.dkr.ecr.us-west-2.amazonaws.com

  build:
    commands:
      - docker build -t mlops .
      - docker tag mlops:latest 846634201516.dkr.ecr.us-west-2.amazonaws.com/mlops:latest
  post_build:
    commands:
      - docker push 846634201516.dkr.ecr.us-west-2.amazonaws.com/mlops:latest
      - aws lambda update-function-code --function-name mlops-inference --image-uri 846634201516.dkr.ecr.us-west-2.amazonaws.com/mlops:latest > /dev/null
